services:

# Torrents indexator
  jackett:
    image: lscr.io/linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow
      - AUTO_UPDATE=true
    volumes:
      - ./config_jackett:/config
    ports:
      - 9117:9117
    restart: unless-stopped
    networks:
      - default

# Torrent client
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    env_file: ".env"
    environment:
      - PUID=1000
      - PGID=1000
      - USER=${LOGIN_TRANSMISSION}
      - PASS=${PASSWORD_TRANSMISSION}
    volumes:
      - /mnt/media/downloads/:/downloads
      - /mnt/media/torrents/:/watch
      - ./config_transmission/:/config
    ports:
      - 9092:9091
      - 51412:51413
      - 51412:51413/udp
    restart: unless-stopped
    networks:
      - default

# Mediaserver
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow
      - LD_LIBRARY_PATH=/opt/cuda/lib64:/usr/local/cuda/lib64
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - CUDADIR=/usr/local/cuda
      - CUDA_HOME=/usr/local/cuda
      - FORCE_CUDA=1
      - CUDA_VISIBLE_DEVICES=0
      - CUDA_LAUNCH_BLOCKING=1
    volumes:
      - ./config_jellyfin:/config
      - /mnt/media/serial:/data/tvshows
      - /mnt/media/video:/data/movies
      - /mnt/media/pictures:/data/pictures
      - /mnt/media/serial:/data/serial
      - /mnt/private_media/video:/data/my_video
      - /mnt/private_media/photo:/data/my_photo
      - /mnt/private_media/vvy_smartphones/camera:/data/camera_vvy
      - /dev/vcsm:/dev/vcsm
      - /dev/vchiq:/dev/vchiq
      - /mnt/private_media/angel_smartphones/camera_device_angel:/data/camera_angel
      - /mnt/media/cources:/data/cources
      - /mnt/media/audiobook:/data/audiobook
      - /mnt/media/music:/data/music
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
 #     - 8920:8920 #optional
    restart: unless-stopped
    devices:
      - /dev/dri:/dev/dri
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidia-modeset:/dev/nvidia-modeset
    dns:
      - 9.9.9.9
    runtime: nvidia
    network_mode: host

# Torrserver
  torrserver:
    image: ghcr.io/yourok/torrserver
    container_name: torrserver
    network_mode: host    # to allow DLNA feature
    environment:
        - TS_PORT=5665
        - TS_DONTKILL=1
        - TS_HTTPAUTH=1
        - TS_CONF_PATH=/opt/ts/config
        - TS_TORR_DIR=/opt/ts/torrents
    volumes:
        - './config_torrserver/CACHE:/opt/ts/torrents'
        - './config_torrserver/CONFIG:/opt/ts/config'
    restart: unless-stopped

# View media from torrentfile
  lampac:
    restart: unless-stopped
    container_name: lampac
    image: immisterio/lampac
    volumes:
     # - /media/downloads:/home/dlna
      - ./config_lampac/init.conf:/home/init.conf
    network_mode: host


networks:
  default:
    external: true
    name: volokzhanin

