version: "2.3"
services:

# Индексатор торрентов
  jackett:
    image: lscr.io/linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Vladivostok
      - AUTO_UPDATE=true
    volumes:
      - ./config_jackett:/config
    ports:
      - 9117:9117
    restart: unless-stopped

# Отслеживание фильмов
  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Vladivostok
    volumes:
      - ./config_radarr:/config
      - /mnt/media/:/downloads 
    ports:
      - 7878:7878
    restart: unless-stopped

# Прокси сервера TOR c мостами 
  tor-privoxy:
    image: registry.gitlab.com/skobkin/torproxy-obfs4
    container_name: tor-privoxy
    ports:
      - "8118:8118/tcp"
      - "9050:9050/tcp"
    volumes:
      - "./config_tor/torrc:/etc/tor/torrc:ro"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "${LOG_MAX_SIZE:-5m}"
        max-file: "${LOG_MAX_FILE:-5}"

# Клиент для закачки торрентов 
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - USER=${LOGIN_TRANSMISSION}
      - PASS=${PASSWORD_TRANSMISSION}
    volumes: 
      - /mnt/media/torrents/:/downloads
      - /mnt/media/torrents/torrents/:/watch
      - ./config_transmission/:/config
    ports:   
      - 9092:9091
      - 51412:51413
      - 51412:51413/udp
    restart: unless-stopped

# Медиасервер
  plex:
    image: lscr.io/linuxserver/plex #nixta/plex-nvdec
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000 
      - PGID=100 
      - PLEX_CLAIM=${PLEX_CLAIM} 
      - UMASK=022
      - VERSION=latest
      #- NVIDIA_VISIBLE_DEVICES=all           
      #- NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
      - VERSION=docker
    volumes:
      - ./transcode_plex:/transcode
      - ./config_plex:/config 
      - /mnt/media/music:/music
      - /mnt/media/cartoon:/cartoon
      - /mnt/media/pictures:/pictures
      - /mnt/media/serial:/serial
      - /mnt/media/video:/video
      - /mnt/backup/my videos/:/my_video
      - /mnt/backup/photo/:/my_pictures
      - /mnt/backup/backup/vvy_smartphones/camera/:/camera_vvy
      - /mnt/backup/backup/angel_smartphones/camera_device_angel/:/camera_angel
      - /mnt/backup/cources/:/cources
    #devices:  
     # - /dev/nvidia0
     # - /dev/nvidia-caps
     # - /dev/nvidiactl
     # - /dev/nvidia-modeset
     # - /dev/nvidia-uvm
     # - /dev/nvidia-uvm-tools
     # - /dev/nvram
    #runtime: nvidia
    restart: unless-stopped
